esphome:
  name: esp32-01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "THGSFcmxAmRLb5PSvpDS7nEBZCeYwe2x+24T0x2OyEw="

ota:
  password: "19995aac489e7eab0577feae9a5f4a8d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-01 Fallback Hotspot"
    password: "y0ltlm7Rryim"

captive_portal:

number:
  - platform: template
    id: pan_value
    name: Pan
    min_value: -100.0
    max_value: 100.0
    unit_of_measurement: "%"
    step: 5
    mode: slider
    optimistic: true
    on_value:
      then:
      - servo.write:
          id: pan
          level: !lambda |-
            return x / 100.0;
        
servo:
  id: pan
  output: pan_output
  restore: true
  transition_length: 4s

output:
  - platform: ledc
    id: pan_output
    pin: GPIO25
    frequency: 50
    channel: 1
