substitutions:
  node_name: pan-tilt
  device_verbose_name: "Pan/Tilt Controller"
  ip_suffix: "144"
  tilt_name: Tilt
  tilt_id: tilt_value
  tilt_gpio: GPIO26
  pan_name: Pan
  pan_id: pan_value
  pan_gpio: GPIO25
  ap_password: "y0ltlm7Rryim"
  board_type: esp32dev

packages:
  wifi: !include common/wifi.yml
  device_base: !include common/device_base.yml
  pan_slider: !include common/pantilt-control.yml

  
api:
  services:
    - service: pan_camera
      variables:
        pan_parameter: float
      then:
      - number.set:
          id: pan_value
          value: !lambda |-
            return id(pan_value).state+pan_parameter;

    - service: tilt_camera
      variables:
        tilt_parameter: float
      then:
      - number.set:
          id: tilt_value
          value: !lambda |-
            return id(tilt_value).state+tilt_parameter;
  
sensor:
  - platform: rotary_encoder
    name: "Gimbal Rotary"
    id: 'rotary2'
    pin_a:
      number: GPIO19
      inverted: true
      mode:
        input: true
    pin_b:
      number: GPIO18
      inverted: true
      mode:
        input: true
        pullup: true
    # min_value: 0
    # max_value: 180
    unit_of_measurement: "°"
    publish_initial_value: true

    on_value:
      then: 
        - if:
            condition:
              switch.is_on: gimbal_toggle
            then:
              - number.set:
                  id: $pan_id
                  value: !lambda |-
                    float pan = id($pan_id).state;
                    float previous = id(rotary_previous);
                    id(rotary_previous) = x; 
                    return pan + x - previous;
            else:
              - number.set:
                  id: $tilt_id
                  value: !lambda |-
                    float tilt = id($tilt_id).state;
                    float previous = id(rotary_previous);
                    id(rotary_previous) = x; 
                    return tilt + x - previous;

globals:
  - id: rotary_previous
    type: float
    restore_value: no  # Strings cannot be saved/restored
    initial_value: '0.0'

switch:
  - platform: template
    id: gimbal_toggle
    name: "Gimbal Toggle Switch"
    optimistic: true

binary_sensor:
  - platform: gpio
    name: "Gimbal Toggle Button"
    pin:
      number: GPIO5
      mode:
        input: true
    on_press:
      then:
        - switch.toggle: gimbal_toggle
    