substitutions:
  node_name: pan02
  device_verbose_name: "Pan/Tilt Controller"
  ip_suffix: "146"

packages:
  wifi: !include common/wifi.yml
  device_base: !include common/device_base.yml
  
api:
  password: ""
