
substitutions:
  node_name: rgb-control
  device_verbose_name: "RGB Control"
  ip_suffix: "31"
  ap_password: "y0ltlm7Rryim"
  board_type: esp32dev

packages:
  wifi: !include common/wifi.yml
  device_base: !include common/device_base.yml

# https://esphome.io/index.html#
esphome:
  includes:
    - custom/glow.h
    - custom/glow
  libraries:
    # - esphome/FastLED=https://github.com/FastLED/FastLED.git

# Enable Home Assistant API
api:
  encryption:
    key: "THGSFcmxAmRLb5PSvpDS7nEBZCeYwe2x+24T0x2OyEw="
  password: ""

# https://esphome.io/components/light/index.html
light:
  - platform: partition
    name: "Grid"
    id: 'grid0'
    segments:
      - id: strip0
        from: 0
        to: 8
      - id: strip1
        from: 0
        to: 8
      - id: strip2
        from: 0
        to: 8
      - id: strip3
        from: 0
        to: 8
    on_turn_on:
      then:
        - lambda: |-
            id(grid_on) = true;
    on_turn_off:
      then:
        - lambda: |-
            id(grid_on) = false;
    effects: !include custom/grid_effects.yml

  - platform: fastled_clockless
    name: "Grid Section 1"
    id: strip0
    chipset: NEOPIXEL
    num_leds: 9
    pin: GPIO33

  - platform: fastled_clockless
    name: "Grid Section 2"
    id: strip1
    chipset: NEOPIXEL
    num_leds: 9
    pin: GPIO14

  - platform: fastled_clockless
    name: "Grid Section 3"
    id: strip2
    chipset: NEOPIXEL
    num_leds: 9
    pin: GPIO27

  - platform: fastled_clockless
    name: "Grid Section 4"
    id: strip3
    chipset: NEOPIXEL
    num_leds: 9
    pin: GPIO13

  - platform: fastled_clockless
    name: "Strip"
    id: strip4
    chipset: WS2811
    rgb_order: BRG
    num_leds: 30
    pin: GPIO26
    effects: !include custom/strip_effects.yml
    on_turn_on:
      then:
        - lambda: |-
            id(strip_on) = true;
    on_turn_off:
      then:
        - lambda: |-
            id(strip_on) = false;

# https://esphome.io/components/sensor/index.html
sensor:
  - platform: rotary_encoder
    name: "Brightness"
    id: 'rotary1'
    pin_a:
      number: GPIO18
      inverted: true
      mode:
        input: true
    pin_b:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true
    min_value: 0
    max_value: 100
    unit_of_measurement: "%"
    publish_initial_value: true
    on_value:
      then:
        - light.turn_on:
            id: grid0
            brightness: !lambda |-
              // output value must be in range 0 - 1.0
              return id(rotary1).state / 100.0;
        - light.turn_on:
            id: strip4
            brightness: !lambda |-
              // output value must be in range 0 - 1.0
              return id(rotary1).state / 100.0;
        
# https://esphome.io/components/switch/index.html
switch:
  - platform: template
    id: led_toggle
    name: "Toggle Switch"
    optimistic: true
    on_turn_on:
      then:
        - light.turn_on: grid0
        - light.turn_on: strip4
    on_turn_off:
      then:
        - light.turn_off: grid0
        - light.turn_off: strip4
  
# https://esphome.io/guides/automations.html?highlight=template#global-variables
globals:
  - id: grid_on
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: strip_on
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: grid_columns
    type: uint16_t
    restore_value: no
    initial_value: '9'
        
# https://esphome.io/components/binary_sensor/index.html
binary_sensor:
  - platform: gpio
    name: "Toggle Button"
    pin:
      number: GPIO19
      mode:
        input: true
    on_press:
      then:
        - switch.toggle: led_toggle
    
